### ISSUE TITLE
Won't execute Python script from classpath

### ISSUE THREAD

**Issue by alexanderkoller** [alexanderkoller/jep-dialogos#1]
The current `JepNode` correctly loads a Python script with a given name from classpath (e.g. `python/plugin.py`), but when it attempts to execute it, the following error is thrown:

```
jep.JepException: <class 'SyntaxError'>: ('multiple statements found while compiling a single statement', ('<string>', 2, 15, 'print("hello")\n'))
        at jep.Jep.eval(Native Method)
        at jep.Jep.eval(Jep.java:451)
        at jep_test_plugin.JepNode.execute(JepNode.java:52)
        at com.clt.diamant.graph.Graph.execute(Graph.java:408)
        at com.clt.diamant.SingleDocument.execute(SingleDocument.java:462)
        at com.clt.diamant.SingleDocument.run(SingleDocument.java:391)
        at com.clt.diamant.gui.SingleDocumentWindow$8.run(SingleDocumentWindow.java:769)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

@akoehn, can you figure out what's going on and fix it?

**Comment by akoehn** [comment]
alexanderkoller writes:

> jep.JepException: <class 'SyntaxError'>: ('multiple statements found
> while compiling a single statement', ('<string>', 2, 15,
> 'print("hello")\n'))

The problem is that eval evaluates a single statement, not a sequence of
statements.  The easiest workaround could be to enable interactive mode
when building the SharedInterpreter and feeding the input line by line
(without interactive == true, each string would need to be complete).

Then, run eval(null) to force evaluation of the last statement in case
it was not clear whether it is complete.

> @akoehn, can you figure out what's going on and fix it?

I can look into that.  In that case, treat the above as “note to self”.

**Comment by alexanderkoller** [comment]
Wait, I think I have a workaround.
